FROM nginx:stable-alpine
LABEL version="1.0"
LABEL author="@edt ASIX-M06"
LABEL subject="NGINX host"
ARG DEBIAN_FRONTEND=noninteractive
COPY default /etc/nginx/conf.d/default.conf
#EXPOSE 443 
#CMD startup.sh
